package com.banger.mobile.domain.model.loan;

import java.math.BigDecimal;
import java.util.Date;

public class LnLoanBalance {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.LOAN_BALANCE_ID
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Integer loanBalanceId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.LOAN_ID
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Integer loanId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.DCRQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Date dcrq;
	private String dcrqStr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.BW
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String bw;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.BWZC
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String bwzc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.BWFZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String bwfz;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.FCSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Integer fcsl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.FCAJSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Integer fcajsl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.JDCSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Integer jdcsl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.JDCAJSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Integer jdcajsl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.HSFS
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String hsfs;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.CSQYRQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private Date csqyrq;
	private String csqyrqStr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.CSQY
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal csqy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.CSQYMX
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String csqymx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.QJLR
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal qjlr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.HKBJ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal hkbj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.QJZZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal qjzz;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.SZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal sz;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.QNTQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal qntq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.ZJ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal zj;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.BZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private BigDecimal bz;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.NOTE
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String note;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.FX
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String fx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column YDWD.LN_LOAN_BALANCE.SM
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	private String sm;
	
	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.LOAN_BALANCE_ID
	 * @return  the value of YDWD.LN_LOAN_BALANCE.LOAN_BALANCE_ID
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Integer getLoanBalanceId() {
		return loanBalanceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.LOAN_BALANCE_ID
	 * @param loanBalanceId  the value for YDWD.LN_LOAN_BALANCE.LOAN_BALANCE_ID
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setLoanBalanceId(Integer loanBalanceId) {
		this.loanBalanceId = loanBalanceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.LOAN_ID
	 * @return  the value of YDWD.LN_LOAN_BALANCE.LOAN_ID
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Integer getLoanId() {
		return loanId;
	}

	

	public void setLoanId(Integer loanId) {
		this.loanId = loanId;
	}

	public void setCsqyrq(Date csqyrq) {
		this.csqyrq = csqyrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.DCRQ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.DCRQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Date getDcrq() {
		return dcrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.DCRQ
	 * @param dcrq  the value for YDWD.LN_LOAN_BALANCE.DCRQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setDcrq(Date dcrq) {
		this.dcrq = dcrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.BW
	 * @return  the value of YDWD.LN_LOAN_BALANCE.BW
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getBw() {
		return bw;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.BW
	 * @param bw  the value for YDWD.LN_LOAN_BALANCE.BW
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setBw(String bw) {
		this.bw = bw;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.BWZC
	 * @return  the value of YDWD.LN_LOAN_BALANCE.BWZC
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getBwzc() {
		return bwzc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.BWZC
	 * @param bwzc  the value for YDWD.LN_LOAN_BALANCE.BWZC
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setBwzc(String bwzc) {
		this.bwzc = bwzc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.BWFZ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.BWFZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getBwfz() {
		return bwfz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.BWFZ
	 * @param bwfz  the value for YDWD.LN_LOAN_BALANCE.BWFZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setBwfz(String bwfz) {
		this.bwfz = bwfz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.FCSL
	 * @return  the value of YDWD.LN_LOAN_BALANCE.FCSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Integer getFcsl() {
		return fcsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.FCSL
	 * @param fcsl  the value for YDWD.LN_LOAN_BALANCE.FCSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setFcsl(Integer fcsl) {
		this.fcsl = fcsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.FCAJSL
	 * @return  the value of YDWD.LN_LOAN_BALANCE.FCAJSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Integer getFcajsl() {
		return fcajsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.FCAJSL
	 * @param fcajsl  the value for YDWD.LN_LOAN_BALANCE.FCAJSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setFcajsl(Integer fcajsl) {
		this.fcajsl = fcajsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.JDCSL
	 * @return  the value of YDWD.LN_LOAN_BALANCE.JDCSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Integer getJdcsl() {
		return jdcsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.JDCSL
	 * @param jdcsl  the value for YDWD.LN_LOAN_BALANCE.JDCSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setJdcsl(Integer jdcsl) {
		this.jdcsl = jdcsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.JDCAJSL
	 * @return  the value of YDWD.LN_LOAN_BALANCE.JDCAJSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Integer getJdcajsl() {
		return jdcajsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.JDCAJSL
	 * @param jdcajsl  the value for YDWD.LN_LOAN_BALANCE.JDCAJSL
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setJdcajsl(Integer jdcajsl) {
		this.jdcajsl = jdcajsl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.HSFS
	 * @return  the value of YDWD.LN_LOAN_BALANCE.HSFS
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getHsfs() {
		return hsfs;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.HSFS
	 * @param hsfs  the value for YDWD.LN_LOAN_BALANCE.HSFS
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setHsfs(String hsfs) {
		this.hsfs = hsfs;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.CSQYRQ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.CSQYRQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public Date getCsqyrq() {
		return csqyrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.CSQYRQ
	 * @param csqyrq  the value for YDWD.LN_LOAN_BALANCE.CSQYRQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void SETCSQYRQ(Date csqyrq) {
		this.csqyrq = csqyrq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.CSQY
	 * @return  the value of YDWD.LN_LOAN_BALANCE.CSQY
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getCsqy() {
		return csqy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.CSQY
	 * @param csqy  the value for YDWD.LN_LOAN_BALANCE.CSQY
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setCsqy(BigDecimal csqy) {
		this.csqy = csqy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.CSQYMX
	 * @return  the value of YDWD.LN_LOAN_BALANCE.CSQYMX
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getCsqymx() {
		return csqymx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.CSQYMX
	 * @param csqymx  the value for YDWD.LN_LOAN_BALANCE.CSQYMX
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setCsqymx(String csqymx) {
		this.csqymx = csqymx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.QJLR
	 * @return  the value of YDWD.LN_LOAN_BALANCE.QJLR
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getQjlr() {
		return qjlr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.QJLR
	 * @param qjlr  the value for YDWD.LN_LOAN_BALANCE.QJLR
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setQjlr(BigDecimal qjlr) {
		this.qjlr = qjlr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.HKBJ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.HKBJ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getHkbj() {
		return hkbj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.HKBJ
	 * @param hkbj  the value for YDWD.LN_LOAN_BALANCE.HKBJ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setHkbj(BigDecimal hkbj) {
		this.hkbj = hkbj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.QJZZ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.QJZZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getQjzz() {
		return qjzz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.QJZZ
	 * @param qjzz  the value for YDWD.LN_LOAN_BALANCE.QJZZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setQjzz(BigDecimal qjzz) {
		this.qjzz = qjzz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.SZ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.SZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getSz() {
		return sz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.SZ
	 * @param sz  the value for YDWD.LN_LOAN_BALANCE.SZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setSz(BigDecimal sz) {
		this.sz = sz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.QNTQ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.QNTQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getQntq() {
		return qntq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.QNTQ
	 * @param qntq  the value for YDWD.LN_LOAN_BALANCE.QNTQ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setQntq(BigDecimal qntq) {
		this.qntq = qntq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.ZJ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.ZJ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getZj() {
		return zj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.ZJ
	 * @param zj  the value for YDWD.LN_LOAN_BALANCE.ZJ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setZj(BigDecimal zj) {
		this.zj = zj;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.BZ
	 * @return  the value of YDWD.LN_LOAN_BALANCE.BZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public BigDecimal getBz() {
		return bz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.BZ
	 * @param bz  the value for YDWD.LN_LOAN_BALANCE.BZ
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setBz(BigDecimal bz) {
		this.bz = bz;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.NOTE
	 * @return  the value of YDWD.LN_LOAN_BALANCE.NOTE
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.NOTE
	 * @param note  the value for YDWD.LN_LOAN_BALANCE.NOTE
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.FX
	 * @return  the value of YDWD.LN_LOAN_BALANCE.FX
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getFx() {
		return fx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.FX
	 * @param fx  the value for YDWD.LN_LOAN_BALANCE.FX
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setFx(String fx) {
		this.fx = fx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column YDWD.LN_LOAN_BALANCE.SM
	 * @return  the value of YDWD.LN_LOAN_BALANCE.SM
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public String getSm() {
		return sm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column YDWD.LN_LOAN_BALANCE.SM
	 * @param sm  the value for YDWD.LN_LOAN_BALANCE.SM
	 * @abatorgenerated  Mon Mar 07 15:26:16 CST 2016
	 */
	public void setSm(String sm) {
		this.sm = sm;
	}

	public String getDcrqStr() {
		return dcrqStr;
	}

	public void setDcrqStr(String dcrqStr) {
		this.dcrqStr = dcrqStr;
	}

	public String getCsqyrqStr() {
		return csqyrqStr;
	}

	public void setCsqyrqStr(String csqyrqStr) {
		this.csqyrqStr = csqyrqStr;
	}

	
}