package com.banger.mobile.domain.model.loan;

import java.math.BigDecimal;

public class LnLoanProfitandlossJyDetail {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private Integer profitandlossJyDetailId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private Integer loanProfitandlossId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private String itemId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private String itemDetailId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_NAME
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private String itemDetailName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_1
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_2
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_3
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_4
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_5
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_6
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_7
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_8
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_9
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_10
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month10;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_11
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month11;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_12
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal month12;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_REP
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    private BigDecimal monthRep;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public Integer getProfitandlossJyDetailId() {
        return profitandlossJyDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @param profitandlossJyDetailId the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setProfitandlossJyDetailId(Integer profitandlossJyDetailId) {
        this.profitandlossJyDetailId = profitandlossJyDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public Integer getLoanProfitandlossId() {
        return loanProfitandlossId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @param loanProfitandlossId the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setLoanProfitandlossId(Integer loanProfitandlossId) {
        this.loanProfitandlossId = loanProfitandlossId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_ID
     *
     * @param itemId the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public String getItemDetailId() {
        return itemDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_ID
     *
     * @param itemDetailId the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setItemDetailId(String itemDetailId) {
        this.itemDetailId = itemDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_NAME
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_NAME
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public String getItemDetailName() {
        return itemDetailName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_NAME
     *
     * @param itemDetailName the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.ITEM_DETAIL_NAME
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setItemDetailName(String itemDetailName) {
        this.itemDetailName = itemDetailName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_1
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_1
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth1() {
        return month1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_1
     *
     * @param month1 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_1
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth1(BigDecimal month1) {
        this.month1 = month1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_2
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_2
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth2() {
        return month2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_2
     *
     * @param month2 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_2
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth2(BigDecimal month2) {
        this.month2 = month2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_3
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_3
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth3() {
        return month3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_3
     *
     * @param month3 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_3
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth3(BigDecimal month3) {
        this.month3 = month3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_4
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_4
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth4() {
        return month4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_4
     *
     * @param month4 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_4
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth4(BigDecimal month4) {
        this.month4 = month4;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_5
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_5
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth5() {
        return month5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_5
     *
     * @param month5 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_5
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth5(BigDecimal month5) {
        this.month5 = month5;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_6
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_6
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth6() {
        return month6;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_6
     *
     * @param month6 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_6
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth6(BigDecimal month6) {
        this.month6 = month6;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_7
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_7
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth7() {
        return month7;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_7
     *
     * @param month7 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_7
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth7(BigDecimal month7) {
        this.month7 = month7;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_8
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_8
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth8() {
        return month8;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_8
     *
     * @param month8 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_8
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth8(BigDecimal month8) {
        this.month8 = month8;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_9
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_9
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth9() {
        return month9;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_9
     *
     * @param month9 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_9
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth9(BigDecimal month9) {
        this.month9 = month9;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_10
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_10
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth10() {
        return month10;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_10
     *
     * @param month10 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_10
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth10(BigDecimal month10) {
        this.month10 = month10;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_11
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_11
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth11() {
        return month11;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_11
     *
     * @param month11 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_11
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth11(BigDecimal month11) {
        this.month11 = month11;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_12
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_12
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonth12() {
        return month12;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_12
     *
     * @param month12 the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_12
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonth12(BigDecimal month12) {
        this.month12 = month12;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_REP
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_REP
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public BigDecimal getMonthRep() {
        return monthRep;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_REP
     *
     * @param monthRep the value for LN_LOAN_PROFITANDLOSS_JY_DETAIL.MONTH_REP
     *
     * @abatorgenerated Mon Mar 14 14:56:35 CST 2016
     */
    public void setMonthRep(BigDecimal monthRep) {
        this.monthRep = monthRep;
    }
}