package com.banger.mobile.domain.model.loan;

public class LnLoanBalanceHousing {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_HOUSING_ID
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    private Integer loanBalanceHousingId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    private Integer loanBalanceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_HOUSING.BUY_DATE
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    private String buyDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_HOUSING.PRICE
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    private String price;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_HOUSING.AREA
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    private String area;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_HOUSING.ADDRESS
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    private String address;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_HOUSING_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_HOUSING_ID
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public Integer getLoanBalanceHousingId() {
        return loanBalanceHousingId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_HOUSING_ID
     *
     * @param loanBalanceHousingId the value for YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_HOUSING_ID
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public void setLoanBalanceHousingId(Integer loanBalanceHousingId) {
        this.loanBalanceHousingId = loanBalanceHousingId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public Integer getLoanBalanceId() {
        return loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_ID
     *
     * @param loanBalanceId the value for YDWD.LN_LOAN_BALANCE_HOUSING.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public void setLoanBalanceId(Integer loanBalanceId) {
        this.loanBalanceId = loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.BUY_DATE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_HOUSING.BUY_DATE
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public String getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.BUY_DATE
     *
     * @param buyDate the value for YDWD.LN_LOAN_BALANCE_HOUSING.BUY_DATE
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public void setBuyDate(String buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.PRICE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_HOUSING.PRICE
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.PRICE
     *
     * @param price the value for YDWD.LN_LOAN_BALANCE_HOUSING.PRICE
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.AREA
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_HOUSING.AREA
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.AREA
     *
     * @param area the value for YDWD.LN_LOAN_BALANCE_HOUSING.AREA
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.ADDRESS
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_HOUSING.ADDRESS
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_HOUSING.ADDRESS
     *
     * @param address the value for YDWD.LN_LOAN_BALANCE_HOUSING.ADDRESS
     *
     * @abatorgenerated Mon Mar 07 16:41:47 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }
}