package com.banger.mobile.domain.model.loan;

public class LnLoanBalanceDebt {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_DEBT_ID
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    private Integer loanBalanceDebtId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    private Integer loanBalanceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_DEBT.TYPE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_DEBT.VALUE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    private String value;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_DEBT.NAME
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_DEBT.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    private String note;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_DEBT_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_DEBT_ID
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public Integer getLoanBalanceDebtId() {
        return loanBalanceDebtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_DEBT_ID
     *
     * @param loanBalanceDebtId the value for YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_DEBT_ID
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public void setLoanBalanceDebtId(Integer loanBalanceDebtId) {
        this.loanBalanceDebtId = loanBalanceDebtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public Integer getLoanBalanceId() {
        return loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_ID
     *
     * @param loanBalanceId the value for YDWD.LN_LOAN_BALANCE_DEBT.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public void setLoanBalanceId(Integer loanBalanceId) {
        this.loanBalanceId = loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.TYPE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_DEBT.TYPE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.TYPE
     *
     * @param type the value for YDWD.LN_LOAN_BALANCE_DEBT.TYPE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.VALUE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_DEBT.VALUE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.VALUE
     *
     * @param value the value for YDWD.LN_LOAN_BALANCE_DEBT.VALUE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.NAME
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_DEBT.NAME
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.NAME
     *
     * @param name the value for YDWD.LN_LOAN_BALANCE_DEBT.NAME
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.NOTE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_DEBT.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_DEBT.NOTE
     *
     * @param note the value for YDWD.LN_LOAN_BALANCE_DEBT.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:07:21 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }
}