package com.banger.mobile.domain.model.loan;

public class LnLoanBalanceVehicle {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_VEHICLE_ID
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private Integer loanBalanceVehicleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private Integer loanBalanceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.BUY_DATE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private String buyDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.PRICE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private String price;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.STATUS
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private String status;
    public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.VEHICLE_NO
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private String vehicleNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_VEHICLE.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    private String note;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_VEHICLE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_VEHICLE_ID
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public Integer getLoanBalanceVehicleId() {
        return loanBalanceVehicleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_VEHICLE_ID
     *
     * @param loanBalanceVehicleId the value for YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_VEHICLE_ID
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void setLoanBalanceVehicleId(Integer loanBalanceVehicleId) {
        this.loanBalanceVehicleId = loanBalanceVehicleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public Integer getLoanBalanceId() {
        return loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_ID
     *
     * @param loanBalanceId the value for YDWD.LN_LOAN_BALANCE_VEHICLE.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void setLoanBalanceId(Integer loanBalanceId) {
        this.loanBalanceId = loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.BUY_DATE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.BUY_DATE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public String getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.BUY_DATE
     *
     * @param buyDate the value for YDWD.LN_LOAN_BALANCE_VEHICLE.BUY_DATE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void setBuyDate(String buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.PRICE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.PRICE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.PRICE
     *
     * @param price the value for YDWD.LN_LOAN_BALANCE_VEHICLE.PRICE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.STATUS
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.STATUS
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.STATUS
     *
     * @param status the value for YDWD.LN_LOAN_BALANCE_VEHICLE.STATUS
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void set(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.VEHICLE_NO
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.VEHICLE_NO
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.VEHICLE_NO
     *
     * @param vehicleNo the value for YDWD.LN_LOAN_BALANCE_VEHICLE.VEHICLE_NO
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.NOTE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_VEHICLE.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_VEHICLE.NOTE
     *
     * @param note the value for YDWD.LN_LOAN_BALANCE_VEHICLE.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:00:53 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }
}