package com.banger.mobile.domain.model.loan;

public class LnLoanBalanceAsset {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ASSET_ID
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    private Integer loanBalanceAssetId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    private Integer loanBalanceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_ASSET.TYPE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_ASSET.NAME
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_ASSET.VALUE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    private String value;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_ASSET.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    private String note;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ASSET_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ASSET_ID
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public Integer getLoanBalanceAssetId() {
        return loanBalanceAssetId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ASSET_ID
     *
     * @param loanBalanceAssetId the value for YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ASSET_ID
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public void setLoanBalanceAssetId(Integer loanBalanceAssetId) {
        this.loanBalanceAssetId = loanBalanceAssetId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public Integer getLoanBalanceId() {
        return loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ID
     *
     * @param loanBalanceId the value for YDWD.LN_LOAN_BALANCE_ASSET.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public void setLoanBalanceId(Integer loanBalanceId) {
        this.loanBalanceId = loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.TYPE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_ASSET.TYPE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.TYPE
     *
     * @param type the value for YDWD.LN_LOAN_BALANCE_ASSET.TYPE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.NAME
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_ASSET.NAME
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.NAME
     *
     * @param name the value for YDWD.LN_LOAN_BALANCE_ASSET.NAME
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.VALUE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_ASSET.VALUE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.VALUE
     *
     * @param value the value for YDWD.LN_LOAN_BALANCE_ASSET.VALUE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.NOTE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_ASSET.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_ASSET.NOTE
     *
     * @param note the value for YDWD.LN_LOAN_BALANCE_ASSET.NOTE
     *
     * @abatorgenerated Mon Mar 07 16:47:18 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }
}