package com.banger.mobile.domain.model.loan;

import java.math.BigDecimal;

public class LnLoanProfitandlossXfDetail {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private Integer profitandlossJyDetailId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private Integer loanProfitandlossId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private String itemId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_NAME
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private String itemDetailName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.PRIOR_YEAR
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private BigDecimal priorYear;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.CURRENT_YEAR
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private BigDecimal currentYear;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.NOTE
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private String note;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    private Integer itemDetailId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public Integer getProfitandlossJyDetailId() {
        return profitandlossJyDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @param profitandlossJyDetailId the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.PROFITANDLOSS_JY_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setProfitandlossJyDetailId(Integer profitandlossJyDetailId) {
        this.profitandlossJyDetailId = profitandlossJyDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public Integer getLoanProfitandlossId() {
        return loanProfitandlossId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @param loanProfitandlossId the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setLoanProfitandlossId(Integer loanProfitandlossId) {
        this.loanProfitandlossId = loanProfitandlossId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_ID
     *
     * @param itemId the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_NAME
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_NAME
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public String getItemDetailName() {
        return itemDetailName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_NAME
     *
     * @param itemDetailName the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_NAME
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setItemDetailName(String itemDetailName) {
        this.itemDetailName = itemDetailName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.PRIOR_YEAR
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.PRIOR_YEAR
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public BigDecimal getPriorYear() {
        return priorYear;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.PRIOR_YEAR
     *
     * @param priorYear the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.PRIOR_YEAR
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setPriorYear(BigDecimal priorYear) {
        this.priorYear = priorYear;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.CURRENT_YEAR
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.CURRENT_YEAR
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public BigDecimal getCurrentYear() {
        return currentYear;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.CURRENT_YEAR
     *
     * @param currentYear the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.CURRENT_YEAR
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setCurrentYear(BigDecimal currentYear) {
        this.currentYear = currentYear;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.NOTE
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.NOTE
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.NOTE
     *
     * @param note the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.NOTE
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public Integer getItemDetailId() {
        return itemDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_ID
     *
     * @param itemDetailId the value for LN_LOAN_PROFITANDLOSS_XF_DETAIL.ITEM_DETAIL_ID
     *
     * @abatorgenerated Mon Mar 14 14:58:46 CST 2016
     */
    public void setItemDetailId(Integer itemDetailId) {
        this.itemDetailId = itemDetailId;
    }
}