package com.banger.mobile.domain.model.loan;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 应收账款
 * @author Administrator
 *
 */
public class LnLoanBalanceReceivable {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_RECEIVABLE_ID
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private Integer loanBalanceReceivableId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private Integer loanBalanceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.KFXM
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private String kfxm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.JE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private BigDecimal je;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.JKFS
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private String jkfs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.FSRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private Date fsrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.YWGXCX
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private String ywgxcx;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.FKFS
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private String fkfs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private Date schkrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKJE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private BigDecimal schkje;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private Date xchkrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKJE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    private BigDecimal xchkje;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_RECEIVABLE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_RECEIVABLE_ID
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public Integer getLoanBalanceReceivableId() {
        return loanBalanceReceivableId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_RECEIVABLE_ID
     *
     * @param loanBalanceReceivableId the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_RECEIVABLE_ID
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setLoanBalanceReceivableId(Integer loanBalanceReceivableId) {
        this.loanBalanceReceivableId = loanBalanceReceivableId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_ID
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public Integer getLoanBalanceId() {
        return loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_ID
     *
     * @param loanBalanceId the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.LOAN_BALANCE_ID
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setLoanBalanceId(Integer loanBalanceId) {
        this.loanBalanceId = loanBalanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.KFXM
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.KFXM
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public String getKfxm() {
        return kfxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.KFXM
     *
     * @param kfxm the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.KFXM
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setKfxm(String kfxm) {
        this.kfxm = kfxm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.JE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.JE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public BigDecimal getJe() {
        return je;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.JE
     *
     * @param je the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.JE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setJe(BigDecimal je) {
        this.je = je;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.JKFS
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.JKFS
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public String getJkfs() {
        return jkfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.JKFS
     *
     * @param jkfs the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.JKFS
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setJkfs(String jkfs) {
        this.jkfs = jkfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.FSRQ
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.FSRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public Date getFsrq() {
        return fsrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.FSRQ
     *
     * @param fsrq the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.FSRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setFsrq(Date fsrq) {
        this.fsrq = fsrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.YWGXCX
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.YWGXCX
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public String getYwgxcx() {
        return ywgxcx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.YWGXCX
     *
     * @param ywgxcx the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.YWGXCX
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setYwgxcx(String ywgxcx) {
        this.ywgxcx = ywgxcx;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.FKFS
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.FKFS
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public String getFkfs() {
        return fkfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.FKFS
     *
     * @param fkfs the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.FKFS
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setFkfs(String fkfs) {
        this.fkfs = fkfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKRQ
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public Date getSchkrq() {
        return schkrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKRQ
     *
     * @param schkrq the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setSchkrq(Date schkrq) {
        this.schkrq = schkrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKJE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKJE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public BigDecimal getSchkje() {
        return schkje;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKJE
     *
     * @param schkje the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.SCHKJE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setSchkje(BigDecimal schkje) {
        this.schkje = schkje;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKRQ
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public Date getXchkrq() {
        return xchkrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKRQ
     *
     * @param xchkrq the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKRQ
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setXchkrq(Date xchkrq) {
        this.xchkrq = xchkrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKJE
     *
     * @return the value of YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKJE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public BigDecimal getXchkje() {
        return xchkje;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKJE
     *
     * @param xchkje the value for YDWD.LN_LOAN_BALANCE_RECEIVABLE.XCHKJE
     *
     * @abatorgenerated Mon Mar 07 15:52:41 CST 2016
     */
    public void setXchkje(BigDecimal xchkje) {
        this.xchkje = xchkje;
    }
}