package com.banger.mobile.domain.model.loan;

public class LnLoanProfitandloss {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private Integer loanProfitandlossId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.LOAN_ID
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private Integer loanId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.BEGIN_MONTH
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private String beginMonth;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.END_MONTH
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private String endMonth;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.END_RATE
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private Integer endRate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.TURNOVER
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private String turnover;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LN_LOAN_PROFITANDLOSS.CROSSCHECK
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    private String crosscheck;
    
    private Boolean flage;//改变起启月份时，是否删除数据
    

    public Boolean getFlage() {
		return flage;
	}

	public void setFlage(Boolean flage) {
		this.flage = flage;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.LOAN_PROFITANDLOSS_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public Integer getLoanProfitandlossId() {
        return loanProfitandlossId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.LOAN_PROFITANDLOSS_ID
     *
     * @param loanProfitandlossId the value for LN_LOAN_PROFITANDLOSS.LOAN_PROFITANDLOSS_ID
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setLoanProfitandlossId(Integer loanProfitandlossId) {
        this.loanProfitandlossId = loanProfitandlossId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.LOAN_ID
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.LOAN_ID
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public Integer getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.LOAN_ID
     *
     * @param loanId the value for LN_LOAN_PROFITANDLOSS.LOAN_ID
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.BEGIN_MONTH
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.BEGIN_MONTH
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public String getBeginMonth() {
        return beginMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.BEGIN_MONTH
     *
     * @param beginMonth the value for LN_LOAN_PROFITANDLOSS.BEGIN_MONTH
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setBeginMonth(String beginMonth) {
        this.beginMonth = beginMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.END_MONTH
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.END_MONTH
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public String getEndMonth() {
        return endMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.END_MONTH
     *
     * @param endMonth the value for LN_LOAN_PROFITANDLOSS.END_MONTH
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setEndMonth(String endMonth) {
        this.endMonth = endMonth;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.END_RATE
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.END_RATE
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public Integer getEndRate() {
        return endRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.END_RATE
     *
     * @param endRate the value for LN_LOAN_PROFITANDLOSS.END_RATE
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setEndRate(Integer endRate) {
        this.endRate = endRate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.TURNOVER
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.TURNOVER
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public String getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.TURNOVER
     *
     * @param turnover the value for LN_LOAN_PROFITANDLOSS.TURNOVER
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setTurnover(String turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LN_LOAN_PROFITANDLOSS.CROSSCHECK
     *
     * @return the value of LN_LOAN_PROFITANDLOSS.CROSSCHECK
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public String getCrosscheck() {
        return crosscheck;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LN_LOAN_PROFITANDLOSS.CROSSCHECK
     *
     * @param crosscheck the value for LN_LOAN_PROFITANDLOSS.CROSSCHECK
     *
     * @abatorgenerated Mon Mar 14 14:51:06 CST 2016
     */
    public void setCrosscheck(String crosscheck) {
        this.crosscheck = crosscheck;
    }
}